//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estadisticas.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Estadisticas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un invocador..
        /// </summary>
        internal static string ERROR_INVOCADOR_OBLIGATORIO {
            get {
                return ResourceManager.GetString("ERROR_INVOCADOR_OBLIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de invocador obligatorio..
        /// </summary>
        internal static string ERROR_NOMBRE_OBLIGATORIO {
            get {
                return ResourceManager.GetString("ERROR_NOMBRE_OBLIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de campeón obligatorio..
        /// </summary>
        internal static string ERROR_NOMBRECAMPEON_OBLIGATORIO {
            get {
                return ResourceManager.GetString("ERROR_NOMBRECAMPEON_OBLIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una partida..
        /// </summary>
        internal static string ERROR_PARTIDA_OBLIGATORIA {
            get {
                return ResourceManager.GetString("ERROR_PARTIDA_OBLIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una ronda..
        /// </summary>
        internal static string ERROR_RONDA_OBLIGATORIA {
            get {
                return ResourceManager.GetString("ERROR_RONDA_OBLIGATORIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona si ha ganado o perdido la partida..
        /// </summary>
        internal static string ERROR_WINLOST_OBLIGATORIO {
            get {
                return ResourceManager.GetString("ERROR_WINLOST_OBLIGATORIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap guardar {
            get {
                object obj = ResourceManager.GetObject("guardar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoKothWinter2015 {
            get {
                object obj = ResourceManager.GetObject("LogoKothWinter2015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que quieres deshacer los cambios?.
        /// </summary>
        internal static string QUESTION_DESCARTAR_CAMBIOS {
            get {
                return ResourceManager.GetString("QUESTION_DESCARTAR_CAMBIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descartar cambios..
        /// </summary>
        internal static string QUESTION_DESCARTAR_TITULO {
            get {
                return ResourceManager.GetString("QUESTION_DESCARTAR_TITULO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas eliminar al Invocador seleccionado? Se borrarán todos sus datos y estadísticas..
        /// </summary>
        internal static string QUESTION_ELIMINAR_INVOCADOR {
            get {
                return ResourceManager.GetString("QUESTION_ELIMINAR_INVOCADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Invocador.
        /// </summary>
        internal static string QUESTION_ELIMINAR_INVOCADOR_TITULO {
            get {
                return ResourceManager.GetString("QUESTION_ELIMINAR_INVOCADOR_TITULO", resourceCulture);
            }
        }
    }
}
